using IEMS.Application.DTOs;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace IEMS.WPF.Pdf
{
    /// <summary>A real, one-click PDF of a fee receipt, rendered from the existing FeeReceiptDto.</summary>
    public class FeeReceiptDocument : IDocument
    {
        private readonly FeeReceiptDto _r;

        public FeeReceiptDocument(FeeReceiptDto receipt)
        {
            _r = receipt;
        }

        // Use "Rs." instead of the ₹ glyph so we don't depend on a font that embeds U+20B9.
        private static string Money(decimal amount) => $"Rs. {amount:N2}";

        public void Compose(IDocumentContainer container)
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A5);
                page.Margin(24);
                page.DefaultTextStyle(t => t.FontSize(10).FontColor(Colors.Black));

                page.Header().Column(col =>
                {
                    col.Item().AlignCenter().Text(_r.SchoolName).Bold().FontSize(15);
                    if (!string.IsNullOrWhiteSpace(_r.SchoolAddress))
                        col.Item().AlignCenter().Text(_r.SchoolAddress).FontSize(9);
                    col.Item().AlignCenter().Text($"Phone: {_r.SchoolPhone}    Email: {_r.SchoolEmail}").FontSize(9);
                    col.Item().PaddingVertical(6).LineHorizontal(1).LineColor(Colors.Grey.Medium);
                    col.Item().AlignCenter().Text("FEE RECEIPT").Bold().FontSize(13).FontColor(Colors.Blue.Darken2);
                });

                page.Content().PaddingVertical(10).Column(col =>
                {
                    col.Spacing(4);

                    col.Item().Row(r =>
                    {
                        r.RelativeItem().Text(t => { t.Span("Receipt No: ").SemiBold(); t.Span(_r.ReceiptNumber); });
                        r.RelativeItem().AlignRight().Text(t => { t.Span("Date: ").SemiBold(); t.Span($"{_r.ReceiptDate:dd/MM/yyyy}"); });
                    });
                    col.Item().Text(t => { t.Span("Academic Year: ").SemiBold(); t.Span(_r.AcademicYear); });

                    col.Item().PaddingTop(6).Text(t => { t.Span("Student: ").SemiBold(); t.Span($"{_r.StudentName}   (Roll No: {_r.StudentNumber})"); });
                    col.Item().Text(t => { t.Span("Class: ").SemiBold(); t.Span($"{_r.ClassName}    Parent Phone: {_r.ParentPhone}"); });

                    col.Item().PaddingTop(8).Table(table =>
                    {
                        table.ColumnsDefinition(c => { c.RelativeColumn(2); c.RelativeColumn(); });

                        void Line(string k, string v)
                        {
                            table.Cell().Border(0.5f).BorderColor(Colors.Grey.Lighten1).Padding(5).Text(k);
                            table.Cell().Border(0.5f).BorderColor(Colors.Grey.Lighten1).Padding(5).AlignRight().Text(v);
                        }

                        Line("Fee Type", _r.FeeType.ToString());
                        Line("Payment Method", _r.PaymentMethod.ToString());
                        Line("Total Fees", Money(_r.TotalFees));
                        if (_r.PreviousBalance > 0) Line("Previous Balance", Money(_r.PreviousBalance));
                        if (_r.LateFee > 0) Line("Late Fee", Money(_r.LateFee));
                        if (_r.Discount > 0) Line("Discount", Money(_r.Discount));

                        table.Cell().Background(Colors.Grey.Lighten3).Border(0.5f).BorderColor(Colors.Grey.Lighten1).Padding(5).Text("Amount Paid").Bold();
                        table.Cell().Background(Colors.Grey.Lighten3).Border(0.5f).BorderColor(Colors.Grey.Lighten1).Padding(5).AlignRight().Text(Money(_r.AmountPaid)).Bold();

                        Line("Remaining Balance", Money(_r.RemainingBalance));
                    });

                    if (!string.IsNullOrWhiteSpace(_r.AmountInWords))
                        col.Item().PaddingTop(6).Text(t => { t.Span("In words: ").SemiBold(); t.Span(_r.AmountInWords).Italic(); });

                    if (!string.IsNullOrWhiteSpace(_r.TransactionId))
                        col.Item().Text($"Transaction ID: {_r.TransactionId}");
                    if (!string.IsNullOrWhiteSpace(_r.ChequeNumber))
                        col.Item().Text($"Cheque/DD No: {_r.ChequeNumber}");
                    if (!string.IsNullOrWhiteSpace(_r.BankName))
                        col.Item().Text($"Bank: {_r.BankName}");
                });

                page.Footer().Column(col =>
                {
                    col.Item().PaddingTop(24).Row(r =>
                    {
                        r.RelativeItem().Text($"Generated by: {_r.GeneratedBy}").FontSize(8);
                        r.RelativeItem().AlignRight().Text("Authorised Signature").FontSize(9);
                    });
                    col.Item().AlignCenter().PaddingTop(6)
                        .Text($"Generated on {_r.GenerationDateTime:dd/MM/yyyy HH:mm}")
                        .FontSize(7).FontColor(Colors.Grey.Medium);
                });
            });
        }
    }
}
